### ISSUE TITLE
Rename "zipcode" to "postal code"

### ISSUE THREAD

**Issue by prodis** [prodis/correios-cep-elixir#17]
## Why

From "Terms" section in https://en.wikipedia.org/wiki/Postal_code:

> CEP: The standard term in Brazil; CEP is an acronym for "código de endereçamento postal" (postal addressing code).

Translation of CEP is **postal** addressing **code**. 

## What

In texts and documentation use "postal code". 

In code, use `postal_code`.

**Comment by lcezermf** [comment]
Hey @prodis can I try to solve this one?

**Comment by prodis** [comment]
Sure @lccezinha! 🙂 

Go ahead and open a PR.

**Comment by prodis** [comment]
https://github.com/prodis/correios-cep-elixir/blob/master/CHANGELOG.md#060---2020-06-17
